### ISSUE TITLE
Need to Update for 1.16 ProtocolChanges

### ISSUE THREAD

**Issue by HighTec90** [korado531m7/StairSeat#14]
Server|CRITICAL > ArgumentCountError: "Too few arguments to funct
ion pocketmine\network\mcpe\protocol\types\EntityLink::__construct(), 0 pa
ssed in phar:///StairSeat.phar/src/korado531m7/StairSeat/StairSeat.php
 on line 120 and exactly 5 expected" (EXCEPTION) in "src/pocketmine/networ
k/mcpe/protocol/types/EntityLink" at line 43

**Comment by korado531m7** [comment]
I have already submitted the latest version to poggit. please wait for approving.

**Comment by HighTec90** [comment]
Ok, i havent seen this ;-) ive start to fix this xD

**Comment by korado531m7** [comment]
xd

**Comment by korado531m7** [comment]
its approved. please download at https://poggit.pmmp.io/p/StairSeat/1.5.2
