### ISSUE TITLE
cant sit

### ISSUE THREAD

**Issue by efor89** [korado531m7/StairSeat#15]
hi
Sitting is not possible because I get up again

**Comment by korado531m7** [comment]
can you send me the video?

**Comment by efor89** [comment]
https://www.youtube.com/watch?v=ogAPBXjwqI0&feature=youtu.be

**Comment by korado531m7** [comment]
thank you for posting. i don't have controller so i don't why. could you test with tap and windows 10 edition?

**Comment by efor89** [comment]
win10 and tap is the same problem yes

**Comment by korado531m7** [comment]
that's strange, because testers haven't confirmed that yet. but, i'll try to find it.

**Comment by efor89** [comment]
I don't know why, but now I can sit

**Comment by korado531m7** [comment]
what, is it fixed?

**Comment by efor89** [comment]
idn but i can sit now ^^

**Comment by korado531m7** [comment]
oh, ok
