### ISSUE TITLE
New option in config

### ISSUE THREAD

**Issue by twk1024** [korado531m7/StairSeat#17]
Hi, I hope there's one more option in the config.

Now the default option of sitting chair is always true, and to disable it, players should type /sit.

But actually, not many players know that command even exists. Because of that, usually, they always ask how should disable this.

So, I think it would be better if there is an option in the config that can set the default option of sitting on a chair.

That means, for example,
if 'default-seat: true', then when players join, they can sit to the chair without anything typed. And they should type /sit to disable it.

And if 'default-seat: false', then when players join, they will not sit on the chair. And they should type /sit to sit on the chair.

**Comment by korado531m7** [comment]
thank you for your suggestion. i'll add the config in the next version!

**Comment by twk1024** [comment]
This function has been implemented in the version 1.5.5, so I will close this. Thanks.
