### ISSUE TITLE
/sit toggle off dont work

### ISSUE THREAD

**Issue by UnEnanoMas** [korado531m7/StairSeat#20]
I'm testing right now on my server that if I use /sit and it sets it to off, I touch a chair and my character sits.

I am using the latest version (dev 30)

**Comment by korado531m7** [comment]
thank you for reporting, please delete the configuration file. if it doesn't work, please report again.

**Comment by UnEnanoMas** [comment]
![image](https://user-images.githubusercontent.com/63286108/93016988-b5761a80-f5c5-11ea-98fe-7672a85472e3.png)

I've removed the plugin files and it still doesn't work

**Comment by korado531m7** [comment]
thank you, i'll check it out.

**Comment by UnEnanoMas** [comment]
I came to tell you that

If you use / sit and disable it, and put a chair in, it doesn't sit you directly.

But

Even if you have the / sit removed, if you click it continues to seat you
