### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SuperAdam47** [korado531m7/StairSeat#3]
Stair kicking player

**Comment by korado531m7** [comment]
thankyou for reporting
please tell me with more information.
how to do it? and what occur the happen?

**Comment by SuperAdam47** [comment]
When you click on the ladder, you sit first, then you go.

**Comment by korado531m7** [comment]
its occur immediately?

**Comment by SuperAdam47** [comment]
Yes

**Comment by korado531m7** [comment]
understood. i'll fix.

**Comment by SuperAdam47** [comment]
now it's worse.

**Comment by korado531m7** [comment]
oh, really?
can you capture screen and upload to me?

**Comment by SuperAdam47** [comment]
once sitting. does not sit again after

**Comment by korado531m7** [comment]
hmm. please walk around after stand up.

**Comment by SuperAdam47** [comment]
I ran and bowed. not fixed

**Comment by korado531m7** [comment]
what pocketmine version did you use? also what version of this plugin did you use?

**Comment by SuperAdam47** [comment]
pmmp: 3.5.6
os: w10

**Comment by korado531m7** [comment]
hmm, unfortunately, i don't have win10 :(
that mean i can't confirm the same environment...
can you test the other platform?

**Comment by SuperAdam47** [comment]
my friend tested same bug

**Comment by korado531m7** [comment]
ok. i'll check again and fix this issue.
thank you.

**Comment by SuperAdam47** [comment]
Thanks for fix

**Comment by korado531m7** [comment]
i submitted this on poggit
