### ISSUE TITLE
We should check if you can sit on a seat

### ISSUE THREAD

**Issue by fuyutsuki** [korado531m7/StairSeat#4]
## Introduction
Currently we can use this plugin and sit on the stairs treated as a chair anywhere as far as you can reach it.  
However, this causes very troublesome on some servers.

For example, that an operator wishes to make a wall so that non-operator can not enter.  
But if you use a staircase block on that wall, players will be able to climb up without permission.

## Proposal
It is easy to fix.  
Just rewrite the code so that you can not sit on the stairs in a place higher than the player's height.

**Comment by korado531m7** [comment]
thank you for reporting.
i completely forgot and couldn't guess what happened on this plugin as you said.

which is better calculate height or register stairs.
of course player can only sit on registered stairs
