### ISSUE TITLE
Optimize Rotation

### ISSUE THREAD

**Issue by SuperAdam47** [korado531m7/StairSeat#5]
The direction of the legs is rotated sideways.

- Its true:

![image](https://user-images.githubusercontent.com/16169771/52639003-4e254f80-2ee4-11e9-8b9b-5e919e77dc18.png)

- Its false:
![image](https://user-images.githubusercontent.com/16169771/52639049-6f863b80-2ee4-11e9-89b1-6f4e116b6753.png)
and 
![image](https://user-images.githubusercontent.com/16169771/52639081-7f058480-2ee4-11e9-9b23-300e6b831d6a.png)

**Comment by korado531m7** [comment]
i've already noticed that.
but i thought that is depends on the minecraft.
i'll try to fix it.

**Comment by SteellgoldEstFrancais** [comment]
Hello someone could give me the id of the brick staircase for the StairSeat plugin because when I put `allow-block-under-id: 108:3` it does not work

**Comment by korado531m7** [comment]
> Hello someone could give me the id of the brick staircase for the StairSeat plugin because when I put `allow-block-under-id: 108:3` it does not work

please write id. don't write damage.
